server.port=${PORT:8080}
server.address=0.0.0.0
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
app.demos-enabled=${DEMOS_ENABLED:false}
app.components-root=node_modules/govuk-frontend/dist/govuk/components
app.assets-root=node_modules/govuk-frontend/dist/govuk/assets
app.frontend-js=node_modules/govuk-frontend/dist/govuk/govuk-frontend.min.js
app.stylesheet=dist/stylesheets/application.css
app.policy-path=baseline/policy.json
app.frontend-version=6.5.1
